server:
  port: 8081
spring:
  application:
    name: "authorization"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    database: "${DB_NAME_AUTH}"
    schema: "${DB_SCHEMA:public}"
aws:
  region: "us-east-1"
  secrets:
    rds: "crediya/rds/auth"
    jwt-key-pair: "jwt/rsa/keys"
